import streamlit as st
import chess
import chess.pgn
import chess.svg
import os
from stockfish_bridge import analyze_fen_sync

# Configure the Streamlit page layout
st.set_page_config(page_title="Chess Blunder Analyzer", page_icon="♟️", layout="wide")

st.title("♟️ Chess Blunder Analyzer")
st.markdown("A lightweight viewer using Streamlit and `chess.svg`.")

# Default PGN file generated by your parser
PGN_FILENAME = "BostonBLRBoy_games.pgn"

@st.cache_data
def load_games(filename):
    """Parses the PGN file into Python objects. Cached to avoid reloading on every UI interaction."""
    games = []
    if not os.path.exists(filename):
        return games
    with open(filename, "r", encoding="utf-8") as f:
        while True:
            game = chess.pgn.read_game(f)
            if game is None:
                break
            games.append(game)
    return games

games = load_games(PGN_FILENAME)

if not games:
    st.warning(f"Could not find `{PGN_FILENAME}` in the current directory. Please ensure you run your Lichess parser first to download the games.")
    st.stop()

# --------------------------
# Sidebar UI
# --------------------------
st.sidebar.header("Game Selection")

# Create a dropdown to select which game to view
game_labels = [f"Game {i+1}: {g.headers.get('White', '?')} vs {g.headers.get('Black', '?')}" for i, g in enumerate(games)]
selected_game_idx = st.sidebar.selectbox("Choose a game:", range(len(games)), format_func=lambda x: game_labels[x])

game = games[selected_game_idx]
moves = list(game.mainline_moves())

st.sidebar.write("---")
st.sidebar.write(f"**White:** {game.headers.get('White', 'Unknown')}")
st.sidebar.write(f"**Black:** {game.headers.get('Black', 'Unknown')}")
st.sidebar.write(f"**Result:** {game.headers.get('Result', '?')}")
st.sidebar.write(f"**Date:** {game.headers.get('Date', '?')}")

st.sidebar.write("---")
st.sidebar.header("Engine Analysis")
auto_analyze = st.sidebar.checkbox("Auto-Analyze Moves", value=False)
depth_setting = st.sidebar.slider("Search Depth", 5, 20, 10, help="Higher depth is more accurate but slower.")

# --------------------------
# Main Panel UI
# --------------------------
st.markdown("### Match Replay")

# Slider to scrub through moves
max_ply = len(moves)
ply = st.slider("Move Slider (Ply)", 0, max_ply, 0)

# Advance the board state to the selected ply
board = game.board()
for i in range(ply):
    board.push(moves[i])

# Grab the last move to highlight it on the board
lastmove = moves[ply-1] if ply > 0 else None

# ---- Engine Analysis & SVG Overlays ----
arrows = []
fill_squares = {}

if ply > 0 and auto_analyze:
    # We need the position *before* the move was played
    board.pop()
    fen_before = board.fen()
    played_move = lastmove.uci()
    board.push(lastmove)
    
    with st.spinner("Analyzing move..."):
        try:
            res = analyze_fen_sync(fen_before, played_move, depth=depth_setting)
            delta = res["delta"]
            best_move_uci = res["engine_best_move"]
            
            st.sidebar.write(f"**Engine Eval:** {res['engine_best_score']:.2f}")
            st.sidebar.write(f"**Played Move Eval:** {res['human_move_score']:.2f}")
            st.sidebar.write(f"**Eval Drop (Delta):** {delta:.2f}")
            
            # If delta > 1.5, classify as a blunder
            if delta > 1.5:
                st.sidebar.error(f"🚨 BLUNDER DETECTED! Delta: {delta:.2f}")
                
                # Plot arrows: Red for played, Green for best
                best_move = chess.Move.from_uci(best_move_uci)
                arrows.append(chess.svg.Arrow(lastmove.from_square, lastmove.to_square, color="red"))
                arrows.append(chess.svg.Arrow(best_move.from_square, best_move.to_square, color="green"))
                
                # Threat Heatmap: Highlight the destination square in soft red
                fill_squares[lastmove.to_square] = "#ffcccc"
            else:
                st.sidebar.success("Good move!")
        except Exception as e:
            st.sidebar.error("Stockfish engine not found or error occurred.")
            st.sidebar.caption(str(e))

# Generate the SVG image of the board
board_svg = chess.svg.board(
    board=board,
    size=450,
    lastmove=lastmove,
    arrows=arrows,
    fill=fill_squares
)

# Render the SVG safely inside Streamlit
st.markdown(f'<div style="display: flex; justify-content: center;">{board_svg}</div>', unsafe_allow_html=True)

# Display what move was just played
if ply > 0:
    board.pop() # Temporarily pop to get the standard algebraic notation (SAN)
    san_move = board.san(lastmove)
    board.push(lastmove)
    
    player = "White" if board.turn == chess.BLACK else "Black"
    st.markdown(f"<h4 style='text-align: center;'>Move {ply}: {player} played <b>{san_move}</b></h4>", unsafe_allow_html=True)

# Output the FEN
st.code(f"FEN: {board.fen()}")
