import streamlit as st
import chess
import chess.pgn
import chess.svg
import os

# Configure the Streamlit page layout
st.set_page_config(page_title="Chess Blunder Analyzer", page_icon="♟️", layout="wide")

st.title("♟️ Chess Blunder Analyzer")
st.markdown("A lightweight viewer using Streamlit and `chess.svg`.")

# Default PGN file generated by your parser
PGN_FILENAME = "BostonBLRBoy_games.pgn"

@st.cache_data
def load_games(filename):
    """Parses the PGN file into Python objects. Cached to avoid reloading on every UI interaction."""
    games = []
    if not os.path.exists(filename):
        return games
    with open(filename, "r", encoding="utf-8") as f:
        while True:
            game = chess.pgn.read_game(f)
            if game is None:
                break
            games.append(game)
    return games

games = load_games(PGN_FILENAME)

if not games:
    st.warning(f"Could not find `{PGN_FILENAME}` in the current directory. Please ensure you run your Lichess parser first to download the games.")
    st.stop()

# --------------------------
# Sidebar UI
# --------------------------
st.sidebar.header("Game Selection")

# Create a dropdown to select which game to view
game_labels = [f"Game {i+1}: {g.headers.get('White', '?')} vs {g.headers.get('Black', '?')}" for i, g in enumerate(games)]
selected_game_idx = st.sidebar.selectbox("Choose a game:", range(len(games)), format_func=lambda x: game_labels[x])

game = games[selected_game_idx]
moves = list(game.mainline_moves())

st.sidebar.write("---")
st.sidebar.write(f"**White:** {game.headers.get('White', 'Unknown')}")
st.sidebar.write(f"**Black:** {game.headers.get('Black', 'Unknown')}")
st.sidebar.write(f"**Result:** {game.headers.get('Result', '?')}")
st.sidebar.write(f"**Date:** {game.headers.get('Date', '?')}")

# --------------------------
# Main Panel UI
# --------------------------
st.markdown("### Match Replay")

# Slider to scrub through moves
max_ply = len(moves)
ply = st.slider("Move Slider (Ply)", 0, max_ply, 0)

# Advance the board state to the selected ply
board = game.board()
for i in range(ply):
    board.push(moves[i])

# Grab the last move to highlight it on the board
lastmove = moves[ply-1] if ply > 0 else None

# Generate the SVG image of the board
board_svg = chess.svg.board(
    board=board,
    size=450,
    lastmove=lastmove,
)

# Render the SVG safely inside Streamlit
st.markdown(f'<div style="display: flex; justify-content: center;">{board_svg}</div>', unsafe_allow_html=True)

# Display what move was just played
if ply > 0:
    board.pop() # Temporarily pop to get the standard algebraic notation (SAN)
    san_move = board.san(lastmove)
    board.push(lastmove)
    
    player = "White" if board.turn == chess.BLACK else "Black"
    st.markdown(f"<h4 style='text-align: center;'>Move {ply}: {player} played <b>{san_move}</b></h4>", unsafe_allow_html=True)

# Output the FEN
st.code(f"FEN: {board.fen()}")

st.markdown("---")
st.info("💡 **Pro Tip**: You can expand this app later by importing `analyze_fen_sync` from `stockfish_bridge.py` and feeding the FEN in to plot the engine evaluation directly alongside the board!")
